### ISSUE TITLE
Silent Auth Failure

### ISSUE THREAD

**Issue by DJMcK** [hapijs/catbox-redis#33]
Currently if authentication fails during `start` the plugin will register successfully. The only indication of the failure is when you attempt to interact with the cache (for me this was `.set`) which will also fail silently.

A little debugging shows that `connect` fires before authentication is attempted - which emits `error` but is too late to stop the plugin registering. Changing `connect` to [`ready`](https://github.com/NodeRedis/node_redis#ready) prevents this happening, and the server will fail on `start`. 

Reading the Redis client's docs it suggests `ready` and `connect` fire at the same time, except when `options.no_ready_check` is set - if I'm interpreting the docs correctly - which I don't believe is being set. If that is the case then perhaps this issue is one for them and not here?

**Comment by LoicMahieu** [comment]
Thanks for reporting this issue.
Yes indeed, if authentication is enabled on redis-server, an event `error` is fired when calling `set` or `get` methods. This behavior is a bug.

At this time, the redis client is created by the internal so we can presume that `no_ready_check` is false. Waiting `ready` instead of `connect` in the internal `start()` looks to be a great fix.
See PR: #37

**Comment by LoicMahieu** [comment]
Released: 1.0.8
